#docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build
services:
  server:
    build:
      context: .
      target: production
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production