#docker-compose up --build
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  server:
    depends_on:
      - mongodb
    build:
      context: .
      target: development  
    ports:
      - "5000:5000"
    volumes:
      - .:/app  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - MONGODB_URI=mongodb://mongodb:27017
    command: dotnet watch run --urls=http://0.0.0.0:5000 